// SPDX-License-Identifier: GPL-2.0

#include <linux/module.h>
#include <linux/init.h>
#include <linux/kobject.h>
#include <linux/sysfs.h>
#include <linux/kernel.h>
#include <linux/slab.h>
#include "okrapm.h"

/* Forward declarations */
static ssize_t install_store(struct kobject *kobj, struct kobj_attribute *attr,
                             const char *buf, size_t count);
static ssize_t remove_store(struct kobject *kobj, struct kobj_attribute *attr,
                            const char *buf, size_t count);
static ssize_t list_show(struct kobject *kobj, struct kobj_attribute *attr,
                         char *buf);

/* Sysfs attributes */
static struct kobj_attribute install_attr = __ATTR_WO(install);
static struct kobj_attribute remove_attr  = __ATTR_WO(remove);
static struct kobj_attribute list_attr    = __ATTR_RO(list);

static struct attribute *okrapm_attrs[] = {
    &install_attr.attr,
    &remove_attr.attr,
    &list_attr.attr,
    NULL,
};

static struct attribute_group attr_group = {
    .attrs = okrapm_attrs,
};

static struct kobject *okrapm_kobj;

static int __init okrapm_init(void)
{
    int ret;
    pr_info("okrapm: initializing kernel package manager module\n");

    okrapm_kobj = kobject_create_and_add("okrapm", kernel_kobj);
    if (!okrapm_kobj) {
        pr_err("okrapm: failed to create kobject\n");
        return -ENOMEM;
    }

    ret = sysfs_create_group(okrapm_kobj, &attr_group);
    if (ret) {
        pr_err("okrapm: failed to create sysfs group (%d)\n", ret);
        kobject_put(okrapm_kobj);
        return ret;
    }

    pr_info("okrapm: sysfs interface created at /sys/okrapm/\n");
    return 0;
}

static void __exit okrapm_exit(void)
{
    pr_info("okrapm: exiting kernel package manager module\n");
    if (okrapm_kobj) {
        sysfs_remove_group(okrapm_kobj, &attr_group);
        kobject_put(okrapm_kobj);
    }
}

/* Sysfs write handler for "install" */
static ssize_t install_store(struct kobject *kobj, struct kobj_attribute *attr,
                             const char *buf, size_t count)
{
    char *pkg_name;
    pr_info("okrapm: install request: %.*s", (int)count, buf);
    pkg_name = kmalloc(count + 1, GFP_KERNEL);
    if (!pkg_name)
        return -ENOMEM;
    memcpy(pkg_name, buf, count);
    pkg_name[count] = '\0';
    okrapm_install(pkg_name);
    kfree(pkg_name);
    return count;
}

/* Sysfs write handler for "remove" */
static ssize_t remove_store(struct kobject *kobj, struct kobj_attribute *attr,
                            const char *buf, size_t count)
{
    char *pkg_name;
    pr_info("okrapm: remove request: %.*s", (int)count, buf);
    pkg_name = kmalloc(count + 1, GFP_KERNEL);
    if (!pkg_name)
        return -ENOMEM;
    memcpy(pkg_name, buf, count);
    pkg_name[count] = '\0';
    okrapm_remove(pkg_name);
    kfree(pkg_name);
    return count;
}

/* Sysfs read handler for "list" */
static ssize_t list_show(struct kobject *kobj, struct kobj_attribute *attr,
                         char *buf)
{
    return okrapm_list(buf, PAGE_SIZE);
}

module_init(okrapm_init);
module_exit(okrapm_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Auto‑Generated by Antigravity");
MODULE_DESCRIPTION("OkraPM kernel package manager – sysfs interface");
